---
# Helpmebot main configuration file.
# 
# All settings are listed here, any optional settings are commented out with their default value.
########################################################################################################
# General miscellaneous bot settings
# 
general:
  commandTrigger: "!"
  userAgent: Helpmebot (+https://helpmebot.org.uk)
  debugChannel: "##helpmebot"
  ownerMask: $a:stwalkerster
  # disableCertificateValidation: false
  # ipInfoDbApiKey:
  # maxMindDatabasePath:
  # prometheusMetricsPort:
  # log4NetConfiguration:
  urlShortener: Helpmebot.CoreServices.Services.UrlShortening.IsGdUrlShorteningService, Helpmebot.CoreServices
  # secondaryUrlShortener:
  
########################################################################################################
# IRC connection configuration
# 
irc:
  clientName: LiberaChat
  hostname: irc.libera.chat
  port: 6697
  ssl: true
  authToServices: false
  nickname:
  # realName: (nickname)
  # username: (nickname)
  # serverPassword:
  # servicesUsername:
  # servicesPassword:
  # restartOnHeavyLag: true
  # reclaimNickFromServices: true
  # pingInterval: 15
  # missedPingLimit: 3

########################################################################################################
# Database configuration
# 
database:
  hostname:
  username:
  password:
  schema:
  # port: 3306
  # charset: utf8mb4


########################################################################################################
# Modules
#
# This is a list of additional modules which can be loaded into the bot for additional functionality.
modules:
  - assembly: Helpmebot.ChannelServices.dll
    configuration:
      - file: Configuration/channel-services.yml
        type: Helpmebot.CategoryWatcher.Configuration.ModuleConfiguration, Helpmebot.ChannelServices
        
  - assembly: Helpmebot.Brain.dll

  - assembly: Helpmebot.CategoryWatcher.dll
    configuration:
      - file: Configuration/categorywatcher.yml
        type: Helpmebot.CategoryWatcher.Configuration.CategoryWatcherConfiguration, Helpmebot.CategoryWatcher
        
  - assembly: Helpmebot.AccountCreations.dll
    configuration:
      - file: Configuration/account-creations.yml
        type: Helpmebot.AccountCreations.Configuration.ModuleConfiguration, Helpmebot.AccountCreations
    
  - assembly: Helpmebot.Commands.dll
    configuration:
      - file: Configuration/afc-data.yml
        type: Helpmebot.Commands.Configuration.AfcCategoryConfiguration, Helpmebot.Commands
        
  - assembly: Helpmebot.WebApi.dll
    configuration:
      - file: Configuration/webapi.yml
        type: WebApiConfiguration, Helpmebot.WebApi

########################################################################################################
# Wikimedia URL shortener configuration (w.wiki)
#
wikimediaShortener:
  mediaWikiApiEndpoint: https://meta.wikimedia.org/w/api.php
  mediaWikiApiUsername:
  mediaWikiApiPassword:
  allowedDomains:
    - ^.*\.wikipedia\.org$
    - ^.*\.wiktionary\.org$
    - ^.*\.wikibooks\.org$
    - ^.*\.wikinews\.org$
    - ^.*\.wikiquote\.org$
    - ^.*\.wikisource\.org$
    - ^.*\.wikiversity\.org$
    - ^.*\.wikivoyage\.org$
    - ^.*\.wikimedia\.org$
    - ^.*\.wikidata\.org$
    - ^.*\.mediawiki\.org$

########################################################################################################
# Command overrides
# 
# This allows you to override a specific command keyword for a specific channel. A good example is to completely disable
# a command in a channel.
# 
# For example, to disable the "!help" command in #mychannel, you would do the following:
#     overrideMap:
#       - keyword: help
#         channel: "#channel"
#         type: "NullCommand"
commandOverrides:
  overrideMap: {}