//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Helpmebot.Attributes.GitRevision("0000000000000000000000000000000000000000")]

// Generated by the MSBuild WriteCodeFragment class on 11/6/2014 10:33:00 PM.

